### ISSUE TITLE
CLPsych program

### ISSUE THREAD

**Issue by hollingk** [cfedermann/acl17-handbook#1]
The CLPsych program is missing 4 papers which should appear under the Poster Session. We had to create a custom Program *and* a custom TOC, but everything as sent to the Program Chairs was correct.

**Comment by callison-burch** [comment]
Can you email your custom items to Christian Federmann <chrife@microsoft.com>?

**Comment by hollingk** [comment]
Done.

**Comment by cfedermann** [comment]
This means the order file was incomplete. I'll merge in the data from your email. Thanks!

**Comment by cfedermann** [comment]
Fixed in commit https://github.com/cfedermann/acl17-handbook/commit/f64a95c81ca16336cfc53f5d641fcdb4a9bf7b14
